esphome:

  name: "antifurto"

  # docs: https://esphome.io/components/esphome#esphome-on-boot

  on_boot:

    priority: 250

    then:

      - switch.turn_on: led_verde

      - switch.turn_off: antifurto


esp32:

  board: esp32dev

  framework:

    type: arduino


# Enable logging

logger:


# Enable Home Assistant API

api:

  encryption:

    key: "XJ6LtIzZJgi9TWQapfW3Xa6YZahzoWrODZbP1Ob5wjQ="

  reboot_timeout: 0s

ota:

  password: "a5fa4262fed6aeaad664f009cd8fccc4"


# docs: https://esphome.io/components/wifi

wifi:

  ssid: !secret wifi_ssid

  password: !secret wifi_password


# docs: https://esphome.io/components/web_server

web_server:

  port: 80


##########


# docs: https://esphome.io/components/switch/

switch:

  # docs: https://esphome.io/components/switch/gpio

  - name: "Led verde"

    id: led_verde

    platform: gpio

    pin: 18


  - name: "Led giallo"

    id: led_giallo

    platform: gpio

    pin: 19


  - name: "Led rosso"

    id: led_rosso

    platform: gpio

    pin: 21


  # docs: https://esphome.io/components/switch/template

  - name: "Antifurto"

    id: antifurto

    platform: template

    optimistic: True

    on_turn_on:

        then:

          - switch.turn_off: led_verde

          - switch.turn_on: led_giallo

    on_turn_off:

      then:

          - switch.turn_on: led_verde

          - switch.turn_off: led_giallo

          - switch.turn_off: led_rosso


# docs: https://esphome.io/components/binary_sensor/

binary_sensor:

  # docs: https://esphome.io/components/binary_sensor/gpio

  - id: bottone

    platform: gpio

    pin:

      number: 32

      inverted: true

      mode:

        input: true

        pullup: true

    on_multi_click:

      - timing:

          - ON for at least 0.1s

        then:

          - switch.toggle: antifurto